name: 'Postman tests action'
description: 'Runs postman tests'

inputs:
  postman_collection_json:
    description: 'the name of the json file with the postman collection to run'
    required: true
  ct_client_id:
    description: 'commercetools client id for running tests'
    required: true
  ct_secret:
    description: 'commercetools secret for running tests'
    required: true
  ct_api_url:
    description: 'commercetools api url'
    required: true
  ct_auth_url:
    description: 'commercetools auth url'
    required: true
  ct_project_id:
    description: 'commercetools project id'
    required: true
  klaviyo_auth_key:
    description: 'Klaviyo auth key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: yarn
    - name: Install newman
      run: |
        yarn global add newman newman-reporter-htmlextra
      shell: bash
    - name: Run e2e tests
      run: |
        newman run ${{ inputs.postman_collection_json }} --bail \
          -r htmlextra \
          --reporter-htmlextra-export newman/htmlreport-${{ inputs.ct_project_id }}.html
          --env-var "ct_client_id=${{ inputs.ct_client_id }}" \
          --env-var "ct_client_secret=${{ inputs.ct_secret }}" \
          --env-var "klaviyoPrivateKey=${{ inputs.klaviyo_auth_key }}" \
          --env-var "klaviyoBaseUrl=https://a.klaviyo.com/" \
          --env-var "ct_auth_url=${{ inputs.ct_auth_url }}" \
          --env-var "ct_host=${{ inputs.ct_api_url }}" \
          --env-var "project-key=${{ inputs.ct_project_id }}" \
          --env-var "customer-key=testcustomer"
      shell: bash
      working-directory: ./src/test/e2e/postman
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: E2E-reports
        path: src/test/e2e/postman/newman
